### ISSUE TITLE
0.10.2 Broken

### ISSUE THREAD

**Issue by MrJerB** [janmg/logstash-input-azure_blob_storage#1]
Code is looking for "use_redis" and no way to pass it in from input config.

**Comment by janmg** [comment]
I pushed a new version 0.10.3 where the use_redis and iplookup is stripped out. I should have declared the config values obsolete, so the defaults would have existed, but I didn't notice that in my testing. I stripped out the use_redis and iplookup because I moved them to a separate logstash-filter-lookup plugin, which I might have to rename to avoid colisions. Thanks for the feedback

**Comment by janmg** [comment]
The use_redis function moved to weblookup.
https://github.com/janmg/logstash-filter-weblookup
Closing the issue.
