### ISSUE TITLE
Plugin hangs at startup and dies after a while and huge resource consumption

### ISSUE THREAD

**Issue by Yann-J** [janmg/logstash-input-azure_blob_storage#13]
Lately our blob feed has been causing Logtash to have lots of difficulties starting up.

I just sent a PR which I think might fix the issue (?): #12

**Comment by janmg** [comment]
I'm merging it. It's confusing because the API uses maxresults, but the ruby library uses max_results as option. I clearly overlooked that.

https://github.com/Azure/azure-storage-ruby/blob/05ea58af3859edda790e769be5beba7fcfb73c0f/blob/lib/azure/storage/blob/container.rb#L608

Before I release the change as 0.11.6, I'll also add an option to skip learning, it seemed like such a good idea when I started this plugin, but it's not nice if you already use the default tags, or know how they look like and your storage account is full of files and the dev doesn't limit the filelisting properly... thanks for your input!
