### ISSUE TITLE
Logstash plugin installation Faraday version mismatch error

### ISSUE THREAD

**Issue by adhiraj-g** [janmg/logstash-input-azure_blob_storage#19]
Hi There,

While trying to install the logstash plugin we faced the following error.
`Using bundled JDK: /usr/share/logstash/jdk
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Validating logstash-input-azure_blob_storage
Installing logstash-input-azure_blob_storage
Plugin version conflict, aborting
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "faraday":
  In snapshot (Gemfile.lock):
    faraday (= 1.7.0)

  In Gemfile:
    logstash-input-azure_blob_storage was resolved to 0.11.3, which depends on
      azure-storage-blob (~> 1.0) was resolved to 1.1.0, which depends on
        azure-core (~> 0.1.13) was resolved to 0.1.15, which depends on
          faraday (~> 0.9)

    logstash-core was resolved to 7.15.0, which depends on
      elasticsearch (~> 7) was resolved to 7.13.3, which depends on
        elasticsearch-transport (= 7.13.3) was resolved to 7.13.3, which depends on
          faraday (~> 1)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

Bundler could not find compatible versions for gem "logstash-input-azure_blob_storage":
  In Gemfile:
    logstash-input-azure_blob_storage`

How to resolve it. Not able to understand. Please help

**Comment by janmg** [comment]
This is about versions. The latest plugin version is currently 0.11.7 you seem to have 0.11.3. The plugin depends on a library to connect to azure storage accounts, that library uses Faraday to make an HTTPS connection. Logstash itself also makes HTTPS connections using the same Faraday, that version I believe has to be the same. The exact version is calculated between the minimum and maximum version of all the gemspecs. So try to do a plugin update and report back the exact version of logstash you are using,than I can try to replicate the problem and see if I need to make changes to support the latest versions

**Comment by janmg** [comment]
I checked the situation with the azure storage ruby that this plugin depends on and they are about to release a version that may not have the strict versioning. Their version 1.1 requires an older version of faraday (0.9 instead of 1.0) and their 2.0 requires an old version of nokogiri. If they release this pull request I can finally use their version 2.0 which otherwise just gives a version mismatch. I'll release my plugin version as 0.12.0 as soon as they release theirs.

https://github.com/Azure/azure-storage-ruby/pull/199

**Comment by adhiraj-g** [comment]
Thanks for the update. @janmg.

**Comment by adhiraj-g** [comment]
Hi @janmg ,

Any updates?

**Comment by janmg** [comment]
The new version of azure-storage-ruby that I depend on was released, but since elasticsearch is using jruby and it's compatible with ruby 2.5, the nokogiri version is still the older version. I will have to release my own version of azure-storage-ruby to bypass this version check. I'll do that in December when I have some bandwidth. Now I'm swamped.

**Comment by janmg** [comment]
I pushed 0.12.0 please check if that works for you. It is based on azure-storage-blob 2.0.3 or higher. Which for me did not have nokogiri issues. I did a bundle update in the logstash folder, which is probably not needed for you, but if you have issues, let me know which ones.
```sudo -u logstash bundle update```

**Comment by adhiraj-g** [comment]
Hi @janmg ,

Hope you had a great Christmas and New Year Break. I did try and install the plugin again. And it worked perfectly, thank you so much. :)
