### ISSUE TITLE
Logstash with plugin  output  failed

### ISSUE THREAD

**Issue by SiberianTiger01** [janmg/logstash-input-azure_blob_storage#32]
Set up an  Azure VM which is  Ubuntu18 with java8  and  logstash plugin  installed  successfully.

set up  network  watcher  to  retrieve  NSG flow logs into storage account  successfully

/etc/logstash/conf.d/logstash.conf:

input {
           azureblob  {
                                 storage_account_name => "flowloghost"
                                 storage_account_key  =>  "......"
                                 container  => "insights-logs-networksecuritygroupflowevent"
               }
}

output  {
             stdout
}

when  kickstart  logstash   with    /usr/share/logstash/bin/logstash -f  /etc/logstash/conf.d/logstash.conf
error  message  triggered,  

how can  I  modify  the  logstash.conf   file

**Comment by janmg** [comment]
azureblob is the plugin from Azure,
https://github.com/Azure/azure-diagnostics-tools/tree/master/Logstash/logstash-input-azureblob

azure_blob_storage is the plugin I started because I couldn't get azureblob to run with higher load. It's not completely compatible with azureblob, but you can try if if works if you replace azureblob with azure_blob_storage

If you have installed my plugin, the configuration examples are in the README.md.
/usr/share/logstash/bin/logstash-plugin install logstash-input-azure_blob_storage

**Comment by SiberianTiger01** [comment]
Thank you very much  for your  suggestion.  I  will  try  it

**Comment by janmg** [comment]
No further information
