### ISSUE TITLE
Parse error when reading NSG Flow Logs v2

### ISSUE THREAD

**Issue by erjosito** [janmg/logstash-input-azure_blob_storage#34]
Hey there! First of all, thanks for creating this plugin! I am trying to use it with the pipeline example of the README.md file for `logtype => nsgflowlogs`, but I get some parsing errors. Example:  `parse error on FLOWLOGS [2023/02/28-20:00] offset: 1614089 length: 1650380`.

Any idea what could be going wrong and how to fix it?

**Comment by janmg** [comment]
Hi, offset means that a big chunk got read already, that's good. If you get parsing errors it must be a json problem around that offset, it's hard to know exactly why. I'm guessing there is a value that the parser doesn't like. It's a long time ago I saw a nsgflowlog that was malformed. could you isolate the file, download it with the storage explorer and see if it is a json fault? I'm happy to write a workaround if I know the exact place where the parsing fails (linenumbers) and which value wasn't expected.

**Comment by janmg** [comment]
The error means that the entry isn't going to be processed, but the parsing should continue on other files. I'll add an exception message to the log entry so there is at least a clue on what happened to the json. I'll make the commit today, you can build the plugin from source if you are comfortable with that, otherwise I'll push a new release to rubygems, so you can do the plugin update with the logstash utilities. 

https://github.com/janmg/logstash-input-azure_blob_storage/blob/master/lib/logstash/inputs/azure_blob_storage.rb#L268
rescue JSON::ParserError => e
                                @logger.error("parse error #{e.message} on #{res[:nsg]} [#{res[:date]}] offset: #{file[:offset]} length:

**Comment by erjosito** [comment]
Wow, that is fantastic! Thanks for your quick answer @janmg. BTW I was trying to follow the official Microsoft docs that use the very old (and apparently unmaintained) Microsoft plugin for blob storage, and the experience was much, much poorer compared to your plugin (even if my pipeline is still wrong, but hopefully I will be able to fix that some day).

I understand you are using this plugin yourself for browsing NSG FLow Logs, right? I am in contact with the Flow Logs Azure Product Team, if you don't mind I would love to put you in contact with them, so that we learn how you use the plugin, and potentially help others that are trying to do the same? If you agree, I would love if you could send me a quick note to jose.moreno@microsoft.com :-)

Thanks again for your awesome work!

**Comment by janmg** [comment]
Hey Jose, any luck with troubleshooting your pipeline? would be great to know if I could fix things regarding the json exception. I pushed 0.12.5 which should at least print out the exception message.

**Comment by erjosito** [comment]
Hey Jan! Sorry for the delay! Yeah, that error is gone, thanks a million for that! I occasionally see now `caught: undefined method '[]' for nil:NilClass while reading resourceId=/SUBSCRIPTIONS/....`, not sure why. Anyhow, I am trying to get some dashboards going on, since I am struggling to extract the fields out of the `message` JSON.

**Comment by erjosito** [comment]
I am probably doing something wrong... I was playing with filters in the pipeline to try to extract JSON fields (initially I was only seeing the `message` field, with all JSON inside as string, but not the individual fields). After giving up because I was getting errors I reverted to my original config, but now it doesn't work.

Here my pipeline:

```
input {
    azure_blob_storage {
        codec => "json"
        storageaccount => "logblahblah"
        access_key => "fasel123"
        container => "insights-logs-networksecuritygroupflowevent"
        logtype => "nsgflowlog"
        prefix => "resourceId=/"
        path_filters => ['**/*.json']
        addfilename => true
        interval => 300
        debug_timer => true
        debug_until => 100
    }
}
output {
    stdout { codec => rubydebug }
    elasticsearch {
        hosts => ["https://localhost:9200"]
        index => "nsg-flow-logs2-%{+xxxx.ww}"
        ssl => true
        ssl_certificate_verification => false
        user => "elastic"
        password => "blah"
    }
}
```

The error I am seeing in the logs is:

```
[2023-03-16T15:45:40,908][ERROR][logstash.javapipeline    ][main][da28334d9e1e80f1e3a5d9c060012c72cd5d6604f3ae7ee513efa95c0d99e389] A plugin had an unrecoverable error. Will restart this plugin.
  Pipeline_id:main
  Plugin: <LogStash::Inputs::AzureBlobStorage container=>"insights-logs-networksecuritygroupflowevent", codec=><LogStash::Codecs::JSON id=>"json_7cad7ed5-02e0-4dec-b1d8-ed0b5356df68", enable_metric=>true, charset=>"UTF-8">, logtype=>"nsgflowlog", debug_timer=>true, path_filters=>["**/*.json"], prefix=>"resourceId=/", storageaccount=>"logblahblah", access_key=><password>, interval=>300, id=>"da28334d9e1e80f1e3a5d9c060012c72cd5d6604f3ae7ee513efa95c0d99e389", debug_until=>100, addfilename=>true, enable_metric=>true, dns_suffix=>"core.windows.net", registry_path=>"data/registry.dat", registry_create_policy=>"resume", skip_learning=>false, file_head=>"{\"records\":[", file_tail=>"]}">
  Error: undefined method `message' for nil:NilClass
  Exception: NoMethodError
  Stack: /usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/logstash-input-azure_blob_storage-0.12.5/lib/logstash/inputs/azure_blob_storage.rb:275:in `block in run'
org/jruby/RubyHash.java:1519:in `each'
/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/logstash-input-azure_blob_storage-0.12.5/lib/logstash/inputs/azure_blob_storage.rb:236:in `run'
/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:411:in `inputworker'
/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:402:in `block in start_input'
```

**Comment by janmg** [comment]
I don't want to pressure you, I also have a day job, but I'm also eager to fix all bugs! Line 236 is when the pipeline starts processing files and line 275 is the line where I added the exception message. I forgot to add the "=> e" So instead of getting the error message, you don't get the error message, but an exception of the exception. Stupid mistake from my side, in the comments above I wrote it correctly. Now as a consequence my pipeline dies when a json error happens.

The original JSON error is still there and I think it's the "caught: undefined method '[]' for nil:NilClass" ... it looks like the json parsing fails on an empty array. It would be great if you can upload your JSON file to my Blobstorage, the access key is in the mail I sent. Otherwise I'll have a think, create a fix and push a new version. Or just send the JSON by mail. I'm happy to include parsing for other common formats if you send the json.

And regarding parsing of the message. Since you set logtype => "nsgflowlog" my pipeline already does the parsing of the nsg flowlogs in line 431. 
ev = rule.merge({:unixtimestamp => tups[0], :src_ip => tups[1], :dst_ip => tups[2], :src_port => tups[3], :dst_port => tups[4], :protocol => tups[5], :direction => tups[6], :decision => tups[7]})

If you set the logtype to the default "raw" then you can do the split and mutate in the filter stage yourself, similar to how azureblob does it. 
split { field => "[records][properties][flows][flows][flowTuples]"}
mutate{
   split => { "[records][resourceId]" => "/"}

Ah, yes ... so this error is within the if logtype == "nsgflowlog" clause, that means that probably the input wasn't the NSG format that was expected and that's why the parsing failed. With a snippet of the JSON I should be able to update the nsgflowlog parsing to account for new formats.

**Comment by erjosito** [comment]
Thanks a lot Jan! I fixed the pipeline, so now I am getting data. However I still see the intermittent error:

```
[2023-03-17T10:02:04,795][ERROR][logstash.inputs.azureblobstorage][main][0940a2d5aa177f12b7119ede070f57d9de177afe8901e96136634a07b065cc4c] parse error undefined method `[]' for nil:NilClass on FLOWLOGS [2023/03/17-09:00] offset: 54235 length: 55567
```

The error message doesn't explicitly describe which blob exactly caused the problem, so I uploaded to your storage account all 4 blobs that match the time `2023/03/17-09:00`

**Comment by janmg** [comment]
Thanks, I tested your files and they parse fine as nsgflowlogs,
I never had a use for systemId, macAddress, category, time, operationName, but if those fields should be added, I'm happy to do so.

I pushed 0.12.6 which after a json parse error should print out the file content, but only if you have set debug_until => x. This will only keep printing errors after the start of the pipeline until x events have been processed. Each individual flowTuple will count as one event. With several hundreds or thousands of events in a file.. 

I did add a fix where, if there are no previously recorded files from the registry. Now only the learning of the headers doesn't always work properly. Learning works by taking any random json file and checking the blob block named A00 and Z00 to learn how the json looks like, this is needed to process json files that have grown since the last reading. That throws some exceptions, but that isn't your issue.

**Comment by mikerosile** [comment]
Hey guys -- I've been following this discussion for the last couple of days because I, too, was facing similar issues.

@janmg I really appreciate you taking the time to develop this plugin.  I would like to see some of those additional fields added, like macAddress for example.

I wouldn't mind contributing some code to this project in the future, but as of right this minute, I'm dealing with a time sensitive situation that requires parsing NSG Flow logs.

Again, I just want to convey my appreciation for the work that is taking place here -- and in the future I'll try to contribute anyway I can .. whether its data collecting, testing, or writing code.

**Comment by mikerosile** [comment]
@janmg I had a situation today where the NSG Flow logs could not be parsed.  Error message below to give you an example.

I have the NSG Flow Log data (JSON file) that I can send you -- just let me know where and how.

> Mar 20 18:47:11 vmcollector logstash[96011]: [2023-03-20T18:47:11,344][ERROR][logstash.inputs.azureblobstorage][main][44150448ac761e9680c81fc38b8d03c5f5612a46a6b640a1937b63c9ec479e04] parse error unexpected token at '-03-20T18:45:26.1641157Z","systemId":"########-####-####-####-########d4dd","macAddress":"002248######","category":"NetworkSecurityGroupFlowEvent","resourceId":"/SUBSCRIPTIONS/########-####-####-####-########BAE5/RESOURCEGROUPS/MIKE-TEST-NETWORK/PROVIDERS/MICROSOFT.NETWORK/NETWORKSECURITYGROUPS/MIKE-TEST-VM1-NSG","operationName":"NetworkSecurityGroupFlowEvents","properties":{"Version":2,"flows":[{"rule":"DefaultRule_AllowInternetOutBound","flows":[{"mac":"002248######","flowTuples":["1679337878,10.0.0.4,40.78.196.51,54518,443,T,O,A,C,35,30865,16,3088","1679337878,10.0.0.4,40.78.196.51,54359,443,T,O,A,C,33,29915,14,2702"]}]},{"rule":"DefaultRule_DenyAllInBound","flows":[{"mac":"002248######","flowTuples":["1679337867,89.248.163.55,10.0.0.4,43330,11480,T,I,D,B,,,,","1679337874,162.142.125.186,10.0.0.4,7171,9120,T,I,D,B,,,,","1679337876,198.235.24.13,10.0.0.4,56352,444,T,I,D,B,,,,","1679337880,23.147.230.11,10.0.0.4,56628,8088,T,I,D,B,,,,","1679337886,89.248.163.72,10.0.0.4,43322,10076,T,I,D,B,,,,","1679337896,162.142.125.237,10.0.0.4,59841,7687,T,I,D,B,,,,","1679337906,89.248.165.118,10.0.0.4,41247,9833,T,I,D,B,,,,","1679337915,89.248.165.194,10.0.0.4,49837,7208,T,I,D,B,,,,","1679337918,205.210.31.3,10.0.0.4,55729,9418,T,I,D,B,,,,"]}]}]}}]}' on MIKE-TEST-VM1-NSG [2023/03/20-18:00] offset: 57534 length: 58790

**Comment by janmg** [comment]
excellent! thanks Mike. It looks like a partial read but starting an offset which is halfway the timestamp. ... the total file length is 58k where 57.5k where already processed. Records can keep growing and every minute a new block-blob can get added to the existing blobs. the first blob-block contains the json start and the last one contains the end. My plugin reads files starting from the offset to the end and adds the json head and tail to a chunk of bytes and feeds it to the jsonparser. In this case it seems that the chuck starts half way the timestamp and if I understand why that happens I can either fix the partial reading or just fix the json before parsing it again. Maybe the blob block of a partial read does not start on a clean json object

I really would like to know how the file is constructed, you can mail it to me or if you are comfortable running jruby then you can add your logstash credentials to the blob_debug program, change the path and filename and run

jruby blob_debug.rb
https://github.com/janmg/logstash-input-azure_blob_storage/blob/master/blob_debug.rb

This should show the blob-blocks names and their sizes. I need those to calculate the offsets.
A00000000000000000000000000000000 12    {"records":[
D672f4bbd95a04209b00dc05d899e3cce 2576  json objects for 1st minute
D7fe0d4f275a84c32982795b0e5c7d3a1 2312  json objects for 2nd minute
Z00000000000000000000000000000000 2     ]}

Thanks for the feedback and help, I'm happy to see the plugin put to good use and I'm eager to keep it in good shape. So thanks for providing the data to make that happen.

from your example this ]}]}]} is accounted for. but these closing curly brackets are not opened from the start... }]}

**Comment by mikerosile** [comment]
I have sent you an email with the original JSON file attached.

Here is the list of blob blocks and their sizes (also included in the email).

```
Name                                         Length Committed
-------                                      ------ ----------
QTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw     12      True
RDkyNGU0YjVkOWE2ZjQyMjdiZTcwODQ1ZWM4N2RmZTMw   1083      True
RDM3ZjRmYmQxMDY1YzQ4NzZhYzQxY2M2YzA2YjgzYTIw    919      True
RDg2YjQ5YjI1MjViOTQ0MmM5MzdjNmRhMWRjNDM1MDNl   1310      True
RDMzMDg1MjkwY2QyNjQ3ZWZiYTAyMGY3MzIwNDc1NTRl   1550      True
RDFlMmI4ZTNhNDcwZDQwNDI4YTM3YTM0ZGFiM2MxMTA2    920      True
RGM3YjNhNGFiMDk2MjRjMTQ4MTE2MTY5MmQ1OTRhY2Ix   1574      True
RGMzMDZiNzFlY2Q1YjRmYTJiYjc4ODBkMTcwODYwYzM2   1326      True
RDkyMjYzNDk4OTFmZDQzYmNhNWE1MDUwNGJiMGE5ODY1   1129      True
RDdhZGZmYjQ4MTgyNzQ4NzFiMWQ3OWRjNjdmOGZhZTJm    960      True
RGFjNTUyOTNkZjQyYzQ1MTE5MzUzMzU3YmRlYTQ3YjU0   1493      True
RDc1N2IzMTE1NzM3ZTRiZGI5N2Y3YjRkNGFjZGI0MTMw   1261      True
RDJhNzQyYmM2ZGRiNDQ2ODg5MGVkN2Y0NDI5MzBlM2Vj    974      True
RDFiOTViNmIyMmRlOTQwOTg5OGU5NTA2NTM2NWQxZDMw   1068      True
RGZlOGQzZmU2MzNiNzQ3NzE4MmI2YzlmNDZlYzRhOWJh   1633      True
RGZjNjc0NGZjN2M5YTQ5MGNiOWE0YWQ2YWM5MmE0YTli   1448      True
RGUwOTFiYWQ2MWU3ODQ2YTNiZTU5ODExY2YyZTlkN2U3   1771      True
RDY2YjYxMGJkMmVlYTQ4NGY5MmMzMDZjOTYyODFhMmVh   1217      True
RDBhZmJlMTlmODYwNjQ1YWE4MzI4M2FlNjE2YzM3OGNh   1018      True
RDJkNTNhNzlkNDkyMzQ1MjRhMDBmMGE4MDI5ODdkMTI0   1502      True
RDU1NjZhNDk5ZTBjOTRjNTNhOWY2MjU2MDBiMzY3MjI3   1163      True
RGJjNjU5MDViN2QzMjQ0MmQ5ZWIyNDdjNGUxM2I5NjA4   1400      True
RDRkOThjY2M4MjI2OTQzYjlhZTY2NTU3MWIyYzg1MTgz   1853      True
RGQ4OWIwMTNmZWM0YTQ4YTNhYTBlOGY5NGM0NmU2MDlm   1452      True
RDQ4MjY0NDk0NmFiMDRjODNhYmMxZGJjYzM2YjY3Yjlj   1424      True
RGFkMzlkZTlkNzAzOTQ0OGRiN2E0MGNjMzk0NWUwOGU4   1560      True
RDI3YWY4MDU2NTU0NTQ1MjZhMWRiMjhhZTQ4OTA0NWQw   1208      True
RDQ1MzZhZDAwNWU0MDRiMjU5NTg2ZjFjYmM5Y2YwYWQw   1064      True
RDZiNzliYWNjNDE3ODQ1ZjM5NjAxMzVjN2JjMjJkNjg3   1564      True
RDQ2M2Q5MmY2MWU0NTRiN2ZhMjNkNjA4OWY1YmYyOTdm    925      True
RDQ0NzkxNmZkNWRiYzQxMDVhOWZjMWU1OTYyYTk2OGFk   1436      True
RDFkMjkxZmEwZmJiODQzYTFhZjM1M2E0NGZlMGZhM2Ix   1445      True
RDA5YWQ3NTBmZTFhOTQ1MjM4YWY5YzE5YTUyNTQxZGEz   1566      True
RGJiYTU5Y2RiYTBhMTQ5ZGU4NmJlZjJjYmVlZWZjMzhk   1197      True
RDg2NzU1MTg2ZWI1NjQ4MDA5YzkxZDM5NTdmNTcxNzJi   1144      True
RDc4ZDBkODg0NjY3OTRlYjhiODliZDdlZmY0NjRhYjkx   1140      True
RDQxOTgzYTVlMDI3MzRhOGQ5YTRkYzAwMWFmZWM0OGNj   1633      True
RDM1NmQyNDliMjRiNzRmNDg5NjFkZDA5ZGU1Mzg2NDJk   1036      True
RDc2MGRiMWE5NDc5YjRmNDQ5OTVlYWZjYzJjOGNkN2E5   1014      True
RGNlZTQ2YTJlMGUyODRkMjViMWE5ZDZlNmMzNTcwOTEz   1209      True
RDI1ZTFhNTE0ZTRlYzQyZDFhNzhmNTBiZGY0MGUyNTNj   1326      True
RGIzMDc0ODRhNjE1OTQwNjk5NGI3YzExZGQyZWM3ZGY3   1277      True
RDM4YWE5NDE3Y2Q1NjQ3MGFiMDgxNzU1ZGUwYjg2MTg0   1425      True
RDk3Y2E2ZDg4NDM5MTQzNzM4YjI5YWY4NWUwOTFiYWZh    795      True
RDg0MDkxZjQ0ZGY2NTQxYmFiNjA5N2UzOGM2YzdmZTdl    897      True
RGEzZDRkMTU5YzJkMjRmNDY4MmNhNDcxYThiZTcwNTZh   1197      True
RDQxMTQzNDMzYjc2YTQ3YjE4MjgwZDY1YWU3NjAxNDVh   1270      True
RGJlYTkyZTUwMjA3NjRmNDBhMDI4ZGFkMGNkNjZhNzI5   1036      True
RDhjNmNlOGNiODQ2MTQ2Nzc5YmUzMGFlYTg0MzkzZTM1   1542      True
RGVhYWQzMGZjYzUxZjQ1MmZiNDQ1NmUyMDczYzMxMTJl    978      True
RDhmMDdmMWM3MDRlMjQyNjM5MjRjYjM1NGU3MTZlNjIx   1379      True
RDdhMWVmMDU1YzNiNDQ1MTdiZGY5OWIzMWIyMmY2ZDcy   1511      True
RGFmZjIyMTBlYzgxMzQ0OTNiM2NmYWU0YTYxYzMzZGY2   1306      True
RGUzMGFkOTdjMDU2ZjQ1MjBiNzVkMjc5MjAxM2YwOTRl   1119      True
RDJiMzE1YjliMjJlNDRjZWI4NTAzOTNmOTMwN2QyZGM4   1096      True
RGRmYTdlZjM2ODAyMjRjNTRhYTk4MTQyZTNjMjI5Y2M5    959      True
RDI3YTdjMmQ5MTZhNjQ5NmM4NWI5ZTNiMmNlN2JhYzBl   1449      True
RDY2NDA5MmMzMmFhYzRjMmViMzI2YjgwOGYwMGU4OWU0   1078      True
RDk5MmM3MWNhYWYxMDQzMTRiYWY1MGE4YTk5NmI5NGJi   1512      True
RDc2ZDkxMmYwNGQ3ODRhZTk4MTdhODRjZTFhZTk1YmIx    961      True
RGNiNjAyOWQwYzkzMjQ2YWE4ZTYyZTlhYjdiNjQ5NTMx   1263      True
WjAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw      2      True

**Comment by janmg** [comment]
During one pass the file was read 14 bytes into the blob-block (57534 bytes, instead of 57520 bytes). Those 14 bytes are missing in the next pass and that triggers the exception. 
RDQxMTQzNDMzYjc2YTQ3YjE4MjgwZDY1YWU3NjAxNDVh

I need some time to think it over, because I thought only committed blocks were read and the logic seems to have read more then what it should have. This may be a time-of-check v.s. time-of-use issue. 

Your printout also helped me figure out why learning the head and tail of the file doesn't work, The blocknames have changed.

**Comment by janmg** [comment]
I commited the changes for 0.12.7 ... I rewrote the partial reading and my tests are now working. Now the amount of data that is read will align to the block size. I then had to struggle getting the offset calculation for the second partial read to be done correctly.  

 12 {record[
  8 {"time"}
  9 ,{"time"}
  9 ,{"time"}
  2 ]}

Step 1 read 22 bytes  0-22   full_read
Step 2 read  8 bytes 22-31   partial_read, strip front comma, prefix with @head (but don't add to offset)
Step 3 read  9 bytes 32-40   partial_read, strip front comma, prefix with @head (but don't add to offset)

I also added a new configuration "addall => true" which adds the mac, operation and category.

It would be nice if someone can do a bit of testing, to see if 0.12.7 works for you, otherwise I'll release the GEM for the new version during the weekend.

**Comment by mikerosile** [comment]
Thanks @janmg for the quick turn-around!  I have installed the plugin, and initial tests look great!  I will be running it for the rest of the day.  If I notice any errors, I'll be sure to report back.

If I do not respond, then assume all is well.

**Comment by janmg** [comment]
I pushed the 0.12.7 gem, it's public now ... I think it solves the parse error. To summarize, there was a timing difference between when checking the filesize was checked and the files were read. I added a block.size checking to respect the json boundaries. Lets see for a week or 2 if problems are reported and then I'll close the issue.

**Comment by janmg** [comment]
No JSON parse errors reported, all seems to work
