### ISSUE TITLE
ERROR The specified blob does not exist

### ISSUE THREAD

**Issue by Xaaame** [janmg/logstash-input-azure_blob_storage#9]
Hello, i have an error when i start logstash.

I have complete correctly the needed parameters with my azure configuration but when i start logstash it does not work cause: The specified blob does not exist.

Can someone help me ? Here's my configuration file:

input {
    azure_blob_storage {
        storageaccount => "my_storageaccount"
        access_key => "my_key"
        container => "monitoring-test"
    }
}

filter {
	mutate {	
		gsub => [
			"message", "\\xE9", "e",
			"message", "\\xEA", "e",
			"message", "\\xE8", "e"
			]
	}
	grok {
	patterns_dir => ["./pattern-maxence"]
		match => { "message" => "%{DATE:log_timestamp}.*?%{WORD:log_type}.*?Serveur .* dans un .* %{ETAT:etat}" }
		#match => { "message" => "%{DATE:log_timestamp}.*?%{WORD:log_type}.*?Initalisation du thread applicatif termin.*e \(r.*sultat = %{INITIALISATION:initialisation}\)" }
		#match => { "message" => "%{DATE:log_timestamp}.*?%{WORD:log_type}.*?Fin du process %{PROCESS:num_process} .* -M\"[0-9]* .*\" -N%{FONCTION:fonction} -d suite .* r.*ception signal [0-9]* non g.*r.*" }
	}
	date {
		match => [ "log_timestamp", "dd:MM:yyyy-HH:mm:ss:SSS" ]
	}
}

output {
	if "_grokparsefailure" not in [tags] {
		elasticsearch {
			hosts => ["localhost:9200"]
			index => "index-azure-maxence"			
		}
	}
	#stdout { codec => rubydebug }
}

**Comment by janmg** [comment]
I assume the specified blob exists, but maybe you can't reach it? Or maybe you can't write into the storageaccount?
The storage account itself is a public URL like https://my_storageaccount.blob.core.windows.net which points to the Azure stores e.g. blob.dub07prdstr03a.store.core.windows.net for storage accounts in Europe North. ... which means that your firewall has to allow connections to 52.239.138.36 or wherever your storage account will be hosted.

By default the plugin will try to find all files (in all directories) and write into the container a file named data/registry. Then read the files one by one and parse them as JSON.

The plugin tries to write the registry after 60 seconds have passed, so it know which files have been read and how many bytes. If the file grows, the additional bytes are read in the next interval. You can write the registry to your local directory so that you don't need to write into your storage_account/container. You can also use debug_until for a couple of bytes until you have some positive hits.

You could add this to the logstash input azure_blob_storage config
codec => "line"
registry_local_path => "/tmp/logstash"
debug_until => 10000

hope this helps

**Comment by Xaaame** [comment]
I have reinstall the plugin and it works. Thx !
